---
version: '2.1'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  collector-routeros:
    build: collector-routeros
    env_file:
      - "${ENV_FILE:-.env}"
    depends_on:
      - redis

